import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource/cormorant-garamond/400.css';
import '@fontsource/cormorant-garamond/400-italic.css';
import '@fontsource/cormorant-garamond/600.css';
import '@fontsource/cormorant-garamond/700.css';
import '@fontsource/eb-garamond/400.css';
import '@fontsource/eb-garamond/400-italic.css';
import '@fontsource/eb-garamond/600.css';
import '@fontsource/eb-garamond/700.css';
import '@fontsource/cinzel/400.css';
import '@fontsource/cinzel/600.css';
import '@fontsource/cinzel/700.css';
import '@fontsource/im-fell-english/400.css';
import '@fontsource/im-fell-english/400-italic.css';
import '@fontsource/great-vibes/400.css';
import '@fontsource/pinyon-script/400.css';
import '@fontsource/marck-script/400.css';
import '@fontsource/noto-serif-armenian/400.css';
import '@fontsource/noto-serif-armenian/600.css';
import '@fontsource/noto-serif-armenian/700.css';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import '@fontsource/inter/700.css';
import '@fontsource/oswald/400.css';
import '@fontsource/oswald/600.css';
import '@fontsource/oswald/700.css';
import '@fontsource/special-elite/400.css';
import './styles/app.css';
import { App } from './app/App';
import { FeedbackProvider } from './app/feedback';
import { SessionProvider } from './app/session';
import { UIProvider } from './app/ui';
import { I18nProvider } from './i18n';

// Offline support: register the service worker generated by vite-plugin-pwa (production builds only).
if (import.meta.env.PROD && 'serviceWorker' in navigator) {
  import('virtual:pwa-register').then(({ registerSW }) => registerSW({ immediate: true })).catch(() => undefined);
}
// Ask the browser to keep IndexedDB data even under storage pressure.
navigator.storage?.persist?.().catch(() => undefined);

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <I18nProvider>
      <SessionProvider>
        <FeedbackProvider>
          <UIProvider>
            <App />
          </UIProvider>
        </FeedbackProvider>
      </SessionProvider>
    </I18nProvider>
  </StrictMode>,
);
